version: '2.1'

services:
  base:
    build: .
    volumes:
      - .:/tldr
      - /tldr/node_modules

  database:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_PASSWORD=Tldr123$$
    ports:
      - 5432

  yopa:
    image: pagarme/yopa:latest
    command: java -Xms64m -Xmx256m -jar uberjar.jar -c /tmp/yopa-in/config.yml -o /tmp/dev-env-aws-regions-override.xml
    ports:
      - 47195
    volumes:
      - ./yopa-config.yml:/tmp/yopa-in/config.yml:ro
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f 'http://localhost:47195?Action=GetQueueUrl&QueueName=receipts",
      ]
      interval: 20s
      retries: 10

  lint:
    extends: base
    command: yarn lint

  test:
    extends: base
    environment:
      - NODE_ENV=test
    command: yarn test

  server:
    extends: base
    command: yarn start
    environment:
      - NODE_ENV=development
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
    links:
      - yopa
      - database

  worker:
    extends: base
    command: yarn start-worker
    environment:
      - NODE_ENV=development
    links:
      - yopa
      - database

